### ISSUE TITLE
measureStart/End Message

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#10]
@jaredjj3 should I continue with multiple measures or would you have another proposal?

**Comment by jaredjj3** [comment]
I think multiple measures will expose some complexity, so I think it's good idea to add a few more features before we revisit maintainability/scalability.

After you do that, I think we need to make a list of features (maybe in the Github projects section?) so that we have a better lit path forward. Do you know if one already exists?

**Comment by jaredjj3** [comment]
C - we need to declare what music notations we want to support, then figure out:

1. if MusicXML can encode it (highly probable)
1. if Vexflow can render it

Without either of these, it doesn't make sense to try to pursue it in this library. We should continue to work the way we've been doing it.
