### ISSUE TITLE
Missing feature in vexflow 5

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#113]
@jaredjj3 do you have any request for vexflow 5?

**Comment by jaredjj3** [comment]
Is there a coloring API? I would like to be able to color elements before and after they're rendered. In stringsync, I have to interact with SVG elements directly, which isn't ideal.

**Comment by rvilarl** [comment]
Yes there is:

- setStyle which modifies an Element
- setGroupStyle which modifies an Element and its associated childs.

**Comment by rvilarl** [comment]
Do you think that we could use vexml in pianoplay? I do not think that osmd will update to vexflow 5 in the medium term.

**Comment by jaredjj3** [comment]
Yes, of course. I don't really know about piano-specific notations, so I could use your help there.

**Comment by jaredjj3** [comment]
@rvilarl, is there something like [getGlyphWidth](https://github.com/0xfe/vexflow/blob/e5f7786c4c5a9b4270c3562992bc5176d2849ee4/tests/formatter_tests.ts#L64) that's public?

I'm interested in precalculating widths in order to perform that calculation that splits a system into several smaller ones. I would replace these [hacky implementations](https://github.com/stringsync/vexml/blob/e64569df0d6f4374a3bccb5998437e736d655ad1/src/rendering/stave.ts#L288-L321) with this vexflow font width calculation API.

**Comment by jaredjj3** [comment]
> Yes there is:
> 
> * setStyle which modifies an Element
> * setGroupStyle which modifies an Element and its associated childs.

I forgot to reply to this. Ok, this is good enough for my use case.

**Comment by rvilarl** [comment]
> @rvilarl, is there something like [getGlyphWidth](https://github.com/0xfe/vexflow/blob/e5f7786c4c5a9b4270c3562992bc5176d2849ee4/tests/formatter_tests.ts#L64) that's public?
> 
> I'm interested in precalculating widths in order to perform that calculation that splits a system into several smaller ones. I would replace these [hacky implementations](https://github.com/stringsync/vexml/blob/e64569df0d6f4374a3bccb5998437e736d655ad1/src/rendering/stave.ts#L288-L321) with this vexflow font width calculation API.

You can use an Element set the text and get the width.

**Comment by jaredjj3** [comment]
Is there a way to get the current font? `Tables.currentMusicFont()` doesn't seem to be public.

**Comment by rvilarl** [comment]
Element takes the fonts directly from the metrics file. The function is Metrics.getFontInfo(), this would take the general one. Metrics.getFontInfo('Accidental') would get the default fonts for accidentals. You can pass the selector to the constructor of Element:
```js
const element = new Element('Clef');
element.setText(Glyphs.fClef);
const width = element.getWidth();
```

**Comment by jaredjj3** [comment]
@rvilarl do you know when https://github.com/0xfe/vexflow/pull/1596 will be in `vxflw-early-access`? Development is slowing down since I have been having to hack around the current limitations in my environment.

**Comment by rvilarl** [comment]
This is already in. @ronyeh could you make a release? I should learn how to do it.

**Comment by ronyeh** [comment]
I made a new alpha release:

https://www.npmjs.com/package/vxflw-early-access?activeTab=versions

https://github.com/vexflow/vexflow/releases/tag/5.0.0-alpha.3

@rvilarl You can make the next release :-) See https://github.com/vexflow/vexflow/issues/116

**Comment by jaredjj3** [comment]
Thanks Ron, it’s working for me.

**Comment by jaredjj3** [comment]
> ```js
> setText
> ```

@rvilarl, it looks like `Glyph` got unexported in https://github.com/vexflow/vexflow/commit/afadd9b557ad653304df58b22af66676965c1e5f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80. Is there another way I could get the glyph?

**Comment by rvilarl** [comment]
Glyph is no longer there. A Glyph is a character in a Font. Element is the new abstraction which is valid for the previous MusicFont and TextFont. TextFormatter is also not there.

**Comment by ronyeh** [comment]
Hi Jared,

Can you tell us what you were doing with the Glyph class? Perhaps Rodrigo can suggest an alternative method. If it is something that is no longer possible in v5, we should investigate to see if we can bring back that functionality somehow. If you find it important, other people might find it important too. 

Thanks!

**Comment by jaredjj3** [comment]
@ronyeh sure, I'm happy to explain in detail.

In `vexml`, there is a procedure that takes a single system and splits them into several smaller systems to fit the renderer width ([code](https://github.com/stringsync/vexml/blob/44e8817a3be276b738ac7c1dcbc1de084d7c3ccd/src/rendering/system.ts#L49)). In order to do this, I need to determine the width for each measure. I identified the minimum width of each measure to be the max(stave modifiers width + the justification width) across all the parts related to that measure. I would like this to be done cheaply.

For the stave modifiers width, it feels like I'm hacking `vexflow`. I render a `vexflow.Stave` at x = 0, and read `vexflow.Stave.getNoteStartX` to determine how much width the modifiers take up. I end up doing this for each modifier separately ([code](https://github.com/stringsync/vexml/blob/0e09bb854ccacdbeafb0902ac8e7eb5e8a13a8c6/src/rendering/stave.ts#L264-L297)).

I don't feel the same way about the measuring justify width, because `vexflow.Formatter` exposes a measuring utility that does exactly what I need. That is, pre calculate the minimum total width needed to accommodate the `vexflow.Voices` ([code](https://github.com/stringsync/vexml/blob/44e8817a3be276b738ac7c1dcbc1de084d7c3ccd/src/rendering/chorus.ts#L182)).

I'm asking for a way to measure the stave modifiers without having to render the entire stave.

**Comment by ronyeh** [comment]
I assume this was easier in v4 (before Glyph was removed)?

Do you have a proposed API for this? (Or did you like the v4 method?) We
can probably figure out a way to implement the getWidth() that you need and
then add it to the API.

**Comment by jaredjj3** [comment]
I only learned about it in this thread https://github.com/stringsync/vexml/issues/113#issuecomment-1742186051, so I never used it. After studying `vexflow` more, I think I found a solution to my problem.

Currently, I'm using `Stave.[addClef|addKeySignature|addTimeSignature]` to add stave modifiers, which also has the convenience of guaranteeing a stave association.

I learned that constructing a `Clef` or `TimeSignature` causes the width to be set, so I can call `StaveModifier.getWidth` on that.

However, `KeySignature.getWidth` has a precondition for a stave to be set, so I'd have to create and associate a dummy `Stave` in order to get a width after constructing it. This feels hacky. How feasible is it to remove the stave association precondition to get a key signature width?

**Comment by rvilarl** [comment]
> However, `KeySignature.getWidth` has a precondition for a stave to be set, so I'd have to create and associate a dummy `Stave` in order to get a width after constructing it. This feels hacky. How feasible is it to remove the stave association precondition to get a key signature width?

I will look into that

**Comment by ronyeh** [comment]
> Is there a way to get the current font? `Tables.currentMusicFont()` doesn't seem to be public. 

Hi! I haven't been following this conversation, so I just saw this comment. 

My current work in progress PR deals with improving the font API. There is already something in flow.ts which exposes the current music font, but this API might change a little due to my PR. 

Hopefully by next week I'll respond to this thread again with the suggest V5 solution to this. (But in the past we have kept tables.ts internal, but exposed some things through flow.ts).

**Comment by rvilarl** [comment]
> @rvilarl, is there something like [getGlyphWidth](https://github.com/0xfe/vexflow/blob/e5f7786c4c5a9b4270c3562992bc5176d2849ee4/tests/formatter_tests.ts#L64) that's public?
> 
> I'm interested in precalculating widths in order to perform that calculation that splits a system into several smaller ones. I would replace these [hacky implementations](https://github.com/stringsync/vexml/blob/e64569df0d6f4374a3bccb5998437e736d655ad1/src/rendering/stave.ts#L288-L321) with this vexflow font width calculation API.

@jaredjj3 we have now Element.measureWidth()

**Comment by jaredjj3** [comment]
Awesome! After I finish #162, I'll use it instead of the current hacky implementation.

**Comment by jaredjj3** [comment]
I'm going to update `vexflow` and try using `Element.measureWidth` now. When that's done, I'll close this issue since things have been discussed in the pull requests.
