### ISSUE TITLE
make an important design decision going forward

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#15]
I think we need to make an important design decision going forward:

1. **Try to adhere to the MusicXML structure as much as possible.** The pros are that MusicXML is a battle-tested spec and there is evidence that we can render most musical notations with it (i.e. we can import a MusicXML file into a lot of popular software and it'll work). The con is that it weakens the `EasyScoreMessage` abstraction. It's trivial to just convert MusicXML to JSON (or some other queryable data structure like an `ElementNode`), and then just pass that to the `vexml.Renderer`. Additionally, it's not great that a `vexml.MessageReceiver` will have to know what to expect in the MusicXML spec, which is very large and has a lot of branches.

2. **Create our own abstractions if it makes message producing and/or receiving easier.** The pros is that we have a mechanism to incrementally collect score information (i.e. the `*Start` and `*End` messages). `vexml.MessageReceiver`s doesn't have to implement a complex "lookahead" mechanism that searches for needed context. Instead they can wait for a message that has it. Another pro is that we can define interfaces that makes it easier to work with `vexflow.EasyScore`. However, this is all at the expense of us misjudging the abstraction boundaries, and having to go back and redefine messages as we add features - just like how you did in this PR.

3. **Some combination of (1) and (2), or something else ???**

My vote is for (2) because one of the motivations of creating the `EasyScoreMessage` abstraction was to make it easy to work with `EasyScore`, which is think is more important than encoding music, which is what MusicXML was made for. After all, we don't have to worry about going from `EasyScoreMessage` -> MusicXML. Managing MusicXML documents is a separate concern outside of this library.

_Originally posted by @jaredjj3 in https://github.com/stringsync/vexml/issues/11#issuecomment-1090488313_

**Comment by rvilarl** [comment]
I have to admit that I see the pros and cons but I do not have a strong oppinion. The particular case of Note and Rest share too many information to separate them, I believe.

**Comment by jaredjj3** [comment]
**My vote is still to move away from the MusicXML spec for our `*Message` structures. If this comment convinces you, feel free to close the issue and just keep this in mind going forward.** Otherwise, I'm happy to keep discussing.

Argument: XML inherently doesn't map well to typesafe JS. We have an opportunity to make `*Message` structures really small in scope which can make it easy to use with `vexml.EasyScore`.

## Note vs. Rest

>The particular case of Note and Rest share too many information to separate them, I believe.

The `NoteMessage` currently looks like this:

```ts
type NoteMessage = {
  msgType: 'note';
  stem: string;
  dots: number;
  pitch: string[];
  type: string;
  duration: string;
  accidental: string;
  voice: string;
  staff: string;
};
```

Rethinking the abstraction, I think we have these relationships (ignoring the `*Message` concept for now):

```ts
const abstract = Symbol('abstract');

type BaseNote = {
  type: typeof abstract;
  dots: number;
  graphicalNoteType: string;
  duration: string;
  voice: string;
  staff: string;
};

type Rest = BaseNote & {
  type: 'rest';
};

type Note = BaseNote & {
  type: 'note';
  stem: string;
  pitch: string[];
  accidental: string;
};
```

If we only use the `NoteMessage` type and we want to make a rest, we would need to implicitly use some default (or make them optional) for  the `stem`, `pitch`, `accidental` properties. Because of this, we can't lean on the TS compiler to tell us if a message refers to a rest or an audible note. At runtime, we have to check if the `note.pitch === ''` to infer this information. If we have more granular types, then we can just check `note.type === 'rest'` and the compiler will know exactly what we're working with. This is one of the advantages of working with smaller types.

The `BaseNote`, `Note`, and `Rest` types are purely for example. I think we should just duplicate the types (aka avoid inheritance) and wait until we see a common pattern amongst `*Message` types before making abstractions like `Base*` types. In other words, we should just have a `NoteMessage` and a `RestMessage` that have a lot of common properties without abstracting those common properties in another type. Maybe both can have an `audible` property to help distinguish the two because someone might expect a rest to be a subtype of note.

---

## Why XML -> typesafe JS is difficult

When I worked on [@stringsync/musicxml](http://github.com/stringsync/musicxml), I quickly learned that the MusicXML spec (and XML in general) is very complex. While XML is more capable than JS, some translation has to happen. XML element attributes simply map to JS object properties, but this is not where the complexity is. XML element _contents_ are **very** difficult to map in a typesafe manner.

For example, take the `<xsd:schema>` spec ([Microsoft docs](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256460(v=vs.100))). Its `Content` spec is this:

```
Content: ((include | import | redefine | annotation)*, (((simpleType | 
complexType | group | attributeGroup) | element | attribute | notation), 
annotation*)*)
```

A concrete example is:

```xml
<xsd:schema>
  <xsd:include></xsd:include>
  <xsd:include></xsd:include>
  <xsd:annotation></xsd:annotation>
  <xsd:group></xsd:group>
  <xsd:annotation></xsd:annotation>
</xsd:schema>
```

The child elements are a list, not a single value. This is a departure from the XML element attribute -> JS object property translation. Some child elements can be repeated (denoted by `*` in the spec), like the first `<xsd:include>`. This isn't too bad. You can have a TS type like this:

```ts
type Etc = any;

type XsdSchema = {
  tagName: 'xsd:schema'
  contents: [
    Array<XsdInclude, XsdImport, Etc>,
    Array<
      Array<XsdSimpleType, XsdComplexType, Etc>,
      Array<XsdAnnotation>
    >
]
};
```

To make this easier to work with, you might create a getter that indexes into the contents array for you (that's what I did in `@stringsync/musicxml`).

```ts
const isXsdInclude = (value: any): value is XsdInclude => {
  return isXsdElement(value) && value.tagName === 'xsd:include';
}

const getXsdIncludes = (xsdSchema: XsdSchema): XsdInclude[] => {
  return xsdSchema.contents[0].filter(isXsdInclude);
}
```

This is a little difficult to develop, but it's not unreasonably complex. Writing unit tests for the above functions is very simple. We now have a typesafe way of managing an XML element's contents.

...or do we?

Take a look at the `xsd:schema` spec again. Arrays of `<xsd:annotation>` children can appear in multiple different parts of the contents array. Writing a simple getter won't work. You need a way to reference either the first, second, or both `<xsd:annotation>` groupings. Each grouping has a specific context, which means you can treat all `<xsd:annotation>`s the same. I got around this in `@stringsync/musicxml` by naming the groupings, and then creating setters/getters for those, but it was really painful to get right.

This incompatibility is a primary reason why I want to move away from the MusicXML spec inside `vexml`.

**Comment by rvilarl** [comment]
Let us go for 2: **Create our own abstractions if it makes message producing and/or receiving easier**
However I sitill have doubts on Note / Rest separation, there will be a lot of code duplication. In the last changes I grouped together `pitch` and `accidental` under an array of `head` to cope with the requirement to sort chords. Now rest is a `note` with an empty array of heads.
I believe though that a `StaffChangeMessage` and `VoiceChangeMessage`will make receiving easier, I will go for them. Let us leave this discussion open.

**Comment by jaredjj3** [comment]
Sounds good. We will gain familiarity with the limitations as we add more features, so we should continue to do that.

**Comment by jaredjj3** [comment]
#90 resolves this.
