### ISSUE TITLE
Vexml site: Sarabande

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#171]
scores with more than two instruments do not render properly.

![image](https://github.com/stringsync/vexml/assets/22865285/f4923a08-e8bd-4b9c-909b-01f512c4719c)

[Sarabande_de_Haendel.zip](https://github.com/stringsync/vexml/files/13403920/Sarabande_de_Haendel.zip)

OSMD

![image](https://github.com/stringsync/vexml/assets/22865285/2daca331-29f8-405f-b3f0-6461e54a14dd)

**Comment by jaredjj3** [comment]
@rvilarl, thanks for reporting this. Would you remake this issue using the new Report an Issue workflow on http://vexml.dev so that we can validate it works e2e please?

It should look like this:

<img width="1230" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/2096f455-6da5-409e-a9cc-9014dcfd18b5">

**Comment by rvilarl** [comment]
> @rvilarl, thanks for reporting this. Would you remake this issue using the new Report an Issue workflow on http://vexml.dev so that we can validate it works e2e please?

done
