### ISSUE TITLE
Inhibition of messages

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#51]
Hi Jared, I will make later today a PR to start handling the lyrics. The lyrics will hide problems with minimal distance formatting. I thought that it might be good to let the user inhibit elements and/or messages on the GUI. What do you think?

**Comment by jaredjj3** [comment]
>on the GUI

Just to clarify, do you mean in the dev app?

I think that the MusicXML document is the sole source of truth. If a user doesn't want something rendered, they should update the MusicXML document and feed it into `vexml`. Another approach is that they can add a middleware to the renderer and filter the messages themselves, but this seems dangerous since they could filter/inject/mutate messages in a way that the renderer (or any other message receiver) is not expecting.

**Comment by rvilarl** [comment]
Yes I meant in the dev app. I will comment on the inhibition on the PR.

**Comment by jaredjj3** [comment]
This is obsolete since we moved off the state machine approach.
